# This is a basic workflow to help you get started with Actions

name: Go_Release
# Controls when the workflow will run
on:
  pull_request:
    types: [closed]
permissions:
  contents: write
jobs:
  on-successful-merge:
    # Этот job запустится ТОЛЬКО если PR был смержен
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: develop
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Get_latest_tag_from_develop
        id: get-tag
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "Latest tag on develop: $LATEST_TAG"
          echo "tag_name=$LATEST_TAG" >> $GITHUB_OUTPUT

      - name: Create_new_tag_in_main
        run: |
          git tag -f ${{ steps.get-tag.outputs.tag_name }}
          git push origin ${{ steps.get-tag.outputs.tag_name }} --force
          
      - name: Create_GitHub_Release
        id: create-release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get-tag.outputs.tag_name }}
          name: Release ${{ steps.get-tag.outputs.tag_name }}
          draft: false
          files: my_program.c
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
